version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres:buster
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cmdrunner_db
  api:
    build: .
    image: elsis/cmdrunner:v0.1
    ports:
      - "8080:7331"
    environment:
      DJANGO_SETTINGS_MODULE: cmdrunner.settings.prod_settings
      SECRET_KEY: "SECURE THIS"
      DATABASE_URL: postgresql://postgres:password@db:5432/cmdrunner_db
    depends_on:
      - db
      - rabbitmq