# Generated by Django 3.2.7 on 2021-09-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('command_id', models.IntegerField(primary_key=True, serialize=False)),
                ('command_name', models.CharField(max_length=10)),
                ('parameters', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('std_in', models.TextField()),
                ('std_out', models.TextField()),
                ('std_err', models.TextField()),
                ('user', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CommandOptions',
            fields=[
                ('option_id', models.IntegerField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=15)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.command')),
            ],
        ),
    ]