# Generated by Django 3.2.7 on 2021-09-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_result_result_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commandoptions',
            name='option_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
