# Generated by Django 3.2.7 on 2021-09-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210918_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='requires_input',
            field=models.BooleanField(default=False),
        ),
    ]
