apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
    service: api-service
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        service: api-service
    spec:
      containers:
      - image: elsis/cmdrunner:v0.1
        name: api
        ports:
        - containerPort: 7331
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: DJANGO_SETTINGS_MODULE
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DATABASE_URL
      restartPolicy: Always
