apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
    service: postgres-service
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        service: postgres-service
    spec:
      containers:
      - image: postgres:buster
        name: postgres
        ports:
        - containerPort: 5432
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_DB
      restartPolicy: Always
