apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
    service: rabbitmq-service
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        service: rabbitmq-service
    spec:
      containers:
      - image: rabbitmq:3.9-management
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always